BloggerBlogBundle_homepage:
    pattern:  /
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
        _method:  GET
        
BloggerBlogBundle_prova:
    pattern:  /prova
    defaults: { _controller: BloggerBlogBundle:Page:show }
    requirements:
        _method:  GET